name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
        python: ["3.7", "3.8", "3.9", "3.10"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install black
        python -m pip install pylint
        python -m pip install pytest
    - name: Lint with pylint
      shell: bash
      run: |
        pylint --disable=line-too-long disable=import-error $(git ls-files '*.py')
    - name: Format with black
      shell: bash
      run: |
        black $(git ls-files '*.py')
    - name: Test with pytest
      run: |
        pytest
        

      
